export const actionTypes = {
  PRODUCTS_COLLECTION_FETCH: 'PRODUCTS/COLLECTION_FETCH',
  PRODUCTS_COLLECTION_FETCH_SUCCESS: 'PRODUCTS/COLLECTION_FETCH_SUCCESS',
  PRODUCTS_COLLECTION_FETCH_ERROR: 'PRODUCTS/COLLECTION_FETCH_ERROR',
};
