export const actionTypes = {
  CUSTOMER_DISCOUNTS_FETCH: 'CUSTOMER/DISCOUNTS_FETCH',
  CUSTOMER_DISCOUNTS_FETCH_SUCCESS: 'CUSTOMER/DISCOUNTS_FETCH_SUCCESS',
  CUSTOMER_DISCOUNTS_FETCH_ERROR: 'CUSTOMER/DISCOUNTS_FETCH_ERROR',
};
